### ISSUE TITLE
Gas on storing mapping on ERC20

### ISSUE THREAD

**Issue by perfogic** [mnill/venom-crash-course-snippets#1]
I'm reading your docs on Venom and you said that the problem on using mapping in ERC20 contract is "Now let's imagine that we have an erc-20 like mem-token contract with one large hashmap of token holders. Everyone who has ever bought this token will be recorded in this contract. Eventually, we will have a situation where users with large balances will have to pay for the storage of those who have only pennies left on their accounts." Anyone can explain me why "we will have a situation where users with large balances will have to pay for the storage of those who have only pennies left on their accounts." I think gas cost for mapping is the same even size increases, because it is saved on **keccak256(keccak256(abi.encode(counts.slot(get from assembly), uint256(key)))** position which can detect directly without any costs such as traversing, etc. So can you explain me what you mean on saying that ? Thanks for your time

**Comment by mnill** [comment]
Hi.

This problem with storage reletaed only

**Comment by mnill** [comment]
Hi.

This problem with storage only related for TON architecture and not related to evm.

Refer to https://venom.guide/tvm/basic (Everything is a bag of cells) In venom contract storage is Tree Of Cell, and as more data stored in contract you need to pay more gas to modify/add data in hashmap.

Please, read https://venom.guide/tvm/basic and feel free to ask any queastions if something will left unclear.

Thanks for your feedback, i'll add remark that this problem is only TVM related.

**Comment by perfogic** [comment]
Ah thank you, sorry for misunderstanding what you mean
